// src/renderer/routes/settings/chat.tsx
import { Button, FileButton, Flex, Slider, Stack, Switch, Text, Textarea, Title, Tooltip } from '@mantine/core'
import { chatSessionSettings, getDefaultPrompt } from '@shared/defaults'
import { IconInfoCircle } from '@tabler/icons-react'
import { createFileRoute } from '@tanstack/react-router'
import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { AssistantAvatar, UserAvatar } from '@/components/Avatar'
import { Divider } from '@/components/Divider'
import { handleImageInputAndSave } from '@/components/Image'
import MaxContextMessageCountSlider from '@/components/MaxContextMessageCountSlider'
import { ScalableIcon } from '@/components/ScalableIcon'
import SliderWithInput from '@/components/SliderWithInput'
import { StorageKeyGenerator } from '@/storage/StoreStorage'
import { useSettingsStore } from '@/stores/settingsStore'
import { add as addToast } from '@/stores/toastActions'

const MAX_IMAGE_SIZE = 5 * 1024 * 1024 // 5MB

export const Route = createFileRoute('/settings/chat')({
  component: RouteComponent,
})

export function RouteComponent() {
  const { t } = useTranslation()
  const { setSettings, ...settings } = useSettingsStore((state) => state)

  return (
    <Stack gap="xxl" p="md">
      <Title order={5}>{t('Chat Settings')}</Title>

      {/* Avatars */}
      <Stack gap="md">
        <Stack gap="xxs">
          <Text fw="600">{t('Edit Avatars')}</Text>
          <Text size="xs" c="chatbox-tertiary">
            {t('Support jpg or png file smaller than 5MB')}
          </Text>
        </Stack>

        {/* User Avatar' */}
        <Stack>
          <Text size="xs" c="chatbox-secondary">
            {t('User Avatar')}
          </Text>
          <Flex align="center" gap="xs">
            <UserAvatar size={56} avatarKey={settings.userAvatarKey} />
            <FileButton
              onChange={(file) => {
                if (file) {
                  if (file.size > MAX_IMAGE_SIZE) {
                    addToast(t('Support jpg or png file smaller than 5MB'))
                    return
                  }
                  const key = StorageKeyGenerator.picture('user-avatar')
                  handleImageInputAndSave(file, key, () => setSettings({ userAvatarKey: key }))
                }
              }}
              accept="image/png,image/jpeg"
            >
              {(props) => (
                <Button {...props} variant="outline" size="xs">
                  {t('Upload Image')}
                </Button>
              )}
            </FileButton>
            {!!settings.userAvatarKey && (
              <Button color="chatbox-gray" size="xs" onClick={() => setSettings({ userAvatarKey: undefined })}>
                {t('Delete')}
              </Button>
            )}
          </Flex>
        </Stack>

        {/* Default Assistant Avatar */}
        <Stack>
          <Text size="xs" c="chatbox-secondary">
            {t('Default Assistant Avatar')}
          </Text>
          <Flex align="center" gap="xs">
            <AssistantAvatar avatarKey={settings.defaultAssistantAvatarKey} size={56} />
            <FileButton
              onChange={(file) => {
                if (file) {
                  if (file.size > MAX_IMAGE_SIZE) {
                    addToast(t('Support jpg or png file smaller than 5MB'))
                    return
                  }
                  const key = StorageKeyGenerator.picture('default-assistant-avatar')
                  handleImageInputAndSave(file, key, () => setSettings({ defaultAssistantAvatarKey: key }))
                }
              }}
              accept="image/png,image/jpeg"
            >
              {(props) => (
                <Button {...props} variant="outline" size="xs">
                  {t('Upload Image')}
                </Button>
              )}
            </FileButton>
            {!!settings.defaultAssistantAvatarKey && (
              <Button
                color="chatbox-gray"
                size="xs"
                onClick={() => setSettings({ defaultAssistantAvatarKey: undefined })}
              >
                {t('Delete')}
              </Button>
            )}
          </Flex>
        </Stack>
      </Stack>

      <Divider />

      {/* Default Settings */}
      <Stack gap="md">
        <Text fw="600">{t('Default Settings for New Conversation')}</Text>
        <Stack gap="xxs">
          <Text fw="500">{t('Prompt')}</Text>
          <Textarea
            value={settings.defaultPrompt || ''}
            autosize
            minRows={1}
            maxRows={12}
            onChange={(e) =>
              setSettings({
                defaultPrompt: e.currentTarget.value,
              })
            }
          />
          <Button
            variant="subtle"
            color="chatbox-gray"
            onClick={() => {
              setSettings({
                defaultPrompt: getDefaultPrompt(),
              })
            }}
            px={3}
            py={6}
            className=" self-start"
          >
            {t('Reset to Default')}
          </Button>
        </Stack>

        <MaxContextMessageCountSlider
          wrapperProps={{ gap: 'xxs' }}
          labelProps={{ fw: undefined }}
          value={settings?.maxContextMessageCount ?? chatSessionSettings().maxContextMessageCount!}
          onChange={(v) => setSettings({ maxContextMessageCount: v })}
        />

        <Stack gap="xxs">
          <Flex align="center" gap="xs">
            <Text size="sm">{t('Temperature')}</Text>
            <Tooltip
              label={t(
                'Modify the creativity of AI responses; the higher the value, the more random and intriguing the answers become, while a lower value ensures greater stability and reliability.'
              )}
              withArrow={true}
              maw={320}
              className="!whitespace-normal"
              zIndex={3000}
              events={{ hover: true, focus: true, touch: true }}
            >
              <ScalableIcon icon={IconInfoCircle} size={20} className="text-chatbox-tint-tertiary" />
            </Tooltip>
          </Flex>

          <SliderWithInput value={settings?.temperature} onChange={(v) => setSettings({ temperature: v })} max={2} />
        </Stack>

        <Stack gap="xxs">
          <Flex align="center" gap="xs">
            <Text size="sm">Top P</Text>
            <Tooltip
              label={t(
                'The topP parameter controls the diversity of AI responses: lower values make the output more focused and predictable, while higher values allow for more varied and creative replies.'
              )}
              withArrow={true}
              maw={320}
              className="!whitespace-normal"
              zIndex={3000}
              events={{ hover: true, focus: true, touch: true }}
            >
              <ScalableIcon icon={IconInfoCircle} size={20} className="text-chatbox-tint-tertiary" />
            </Tooltip>
          </Flex>

          <SliderWithInput value={settings?.topP} onChange={(v) => setSettings({ topP: v })} max={1} />
        </Stack>

        <Stack gap="xxs">
          <Flex align="center" gap="xs" justify="space-between">
            <Text size="sm">{t('Stream output')}</Text>
            <Switch
              // label={t('Stream output')}
              checked={settings?.stream ?? true}
              onChange={(v) => setSettings({ stream: v.target.checked })}
            />
          </Flex>
        </Stack>
      </Stack>
      <Divider />

      {/* Conversation Settings */}
      <Stack gap="md">
        <Text fw="600">{t('Conversation Settings')}</Text>

        {/* Display */}
        <Stack gap="sm">
          <Text c="chatbox-tertiary">{t('Display')}</Text>

          <Switch
            label={t('show message word count')}
            checked={settings.showWordCount}
            onChange={() =>
              setSettings((draft) => {
                draft.showWordCount = !draft.showWordCount
              })
            }
          />

          {/* <Switch
            label={t('show message token count')}
            checked={settings.showTokenCount}
            onChange={() =>
              setSettings({
                showTokenCount: !settings.showTokenCount,
              })
            }
          /> */}

          <Switch
            label={t('show message token usage')}
            checked={settings.showTokenUsed}
            onChange={() =>
              setSettings({
                showTokenUsed: !settings.showTokenUsed,
              })
            }
          />

          <Switch
            label={t('show model name')}
            checked={settings.showModelName}
            onChange={() =>
              setSettings({
                showModelName: !settings.showModelName,
              })
            }
          />

          <Switch
            label={t('show message timestamp')}
            checked={settings.showMessageTimestamp}
            onChange={() =>
              setSettings({
                showMessageTimestamp: !settings.showMessageTimestamp,
              })
            }
          />

          <Switch
            label={t('show first token latency')}
            checked={settings.showFirstTokenLatency}
            onChange={() =>
              setSettings({
                showFirstTokenLatency: !settings.showFirstTokenLatency,
              })
            }
          />
        </Stack>

        {/* Function */}
        <Stack gap="sm">
          <Text c="chatbox-tertiary">{t('Function')}</Text>

          <Switch
            label={t('Auto-collapse code blocks')}
            checked={settings.autoCollapseCodeBlock}
            onChange={() =>
              setSettings({
                autoCollapseCodeBlock: !settings.autoCollapseCodeBlock,
              })
            }
          />
          <Switch
            label={t('Auto-Generate Chat Titles')}
            checked={settings.autoGenerateTitle}
            onChange={() =>
              setSettings({
                ...settings,
                autoGenerateTitle: !settings.autoGenerateTitle,
              })
            }
          />
          <Switch
            label={t('Spell Check')}
            checked={settings.spellCheck}
            onChange={() =>
              setSettings({
                ...settings,
                spellCheck: !settings.spellCheck,
              })
            }
          />
          <Switch
            label={t('Markdown Rendering')}
            checked={settings.enableMarkdownRendering}
            onChange={() =>
              setSettings({
                ...settings,
                enableMarkdownRendering: !settings.enableMarkdownRendering,
              })
            }
          />
          <Switch
            label={t('LaTeX Rendering (Requires Markdown)')}
            checked={settings.enableLaTeXRendering}
            onChange={() =>
              setSettings({
                ...settings,
                enableLaTeXRendering: !settings.enableLaTeXRendering,
              })
            }
          />
          <Switch
            label={t('Mermaid Diagrams & Charts Rendering')}
            checked={settings.enableMermaidRendering}
            onChange={() =>
              setSettings({
                ...settings,
                enableMermaidRendering: !settings.enableMermaidRendering,
              })
            }
          />
          <Switch
            label={t('Inject default metadata')}
            checked={settings.injectDefaultMetadata}
            description={t('e.g., Model Name, Current Date')}
            onChange={() =>
              setSettings({
                ...settings,
                injectDefaultMetadata: !settings.injectDefaultMetadata,
              })
            }
          />
          <Switch
            label={t('Auto-preview artifacts')}
            checked={settings.autoPreviewArtifacts}
            description={t('Automatically render generated artifacts (e.g., HTML with CSS, JS, Tailwind)')}
            onChange={() =>
              setSettings({
                ...settings,
                autoPreviewArtifacts: !settings.autoPreviewArtifacts,
              })
            }
          />
          <Switch
            label={t('Paste long text as a file')}
            checked={settings.pasteLongTextAsAFile}
            description={t(
              'Pasting long text will automatically insert it as a file, keeping chats clean and reducing token usage with prompt caching.'
            )}
            onChange={() =>
              setSettings({
                ...settings,
                pasteLongTextAsAFile: !settings.pasteLongTextAsAFile,
              })
            }
          />
        </Stack>
      </Stack>

      <Divider />

      {/* Context Management */}
      <ContextManagementSection />
    </Stack>
  )
}

function ContextManagementSection() {
  const { t } = useTranslation()
  const { setSettings, ...settings } = useSettingsStore((state) => state)

  // Get strategy hint based on threshold value
  const strategyHint = useMemo(() => {
    const threshold = settings.compactionThreshold ?? 0.6
    if (threshold <= 0.5) {
      return t('Cost Priority: Compacts early to save tokens, may lose some context')
    }
    if (threshold >= 0.8) {
      return t('Context Priority: Preserves more context, uses more tokens')
    }
    return t('Balanced: Good balance between cost and context preservation')
  }, [settings.compactionThreshold, t])

  return (
    <Stack gap="xl">
      <Text fw="600">{t('Context Management')}</Text>

      {/* Auto Compaction Toggle */}
      <Stack gap="sm">
        <Flex align="center" gap="xs" justify="space-between">
          <Flex align="center" gap="xs">
            <Text size="sm">{t('Auto Compaction')}</Text>
            <Tooltip
              label={t(
                'Automatically summarize and compact conversation history when context size exceeds the threshold, preserving key information while reducing token usage.'
              )}
              withArrow={true}
              maw={320}
              className="!whitespace-normal"
              zIndex={3000}
              events={{ hover: true, focus: true, touch: true }}
            >
              <ScalableIcon icon={IconInfoCircle} size={20} className="text-chatbox-tint-tertiary" />
            </Tooltip>
          </Flex>
          <Switch
            checked={settings.autoCompaction ?? true}
            onChange={() =>
              setSettings({
                autoCompaction: !(settings.autoCompaction ?? true),
              })
            }
          />
        </Flex>
        <Text c="chatbox-tertiary" size="xs">
          {t('When enabled, conversations will be automatically summarized to manage context window usage.')}
        </Text>
      </Stack>

      {/* Compaction Threshold Slider */}
      <Stack gap="sm">
        <Flex align="center" gap="xs">
          <Text size="sm">{t('Compaction Threshold')}</Text>
          <Tooltip
            label={t(
              'The percentage of context window usage that triggers automatic compaction. Lower values save tokens but may lose context earlier.'
            )}
            withArrow={true}
            maw={320}
            className="!whitespace-normal"
            zIndex={3000}
            events={{ hover: true, focus: true, touch: true }}
          >
            <ScalableIcon icon={IconInfoCircle} size={20} className="text-chatbox-tint-tertiary" />
          </Tooltip>
        </Flex>

        <Stack gap="xs" mt="xs">
          <Slider
            min={0.4}
            max={0.9}
            step={0.05}
            value={settings.compactionThreshold ?? 0.6}
            onChange={(v) => setSettings({ compactionThreshold: v })}
            label={(v) => `${Math.round(v * 100)}%`}
            disabled={!(settings.autoCompaction ?? true)}
          />
          <Flex justify="space-between" px={2}>
            <Text size="xs" c="chatbox-tertiary">
              {t('Cost')}
            </Text>
            <Text size="xs" c="chatbox-tertiary">
              {t('Context')}
            </Text>
          </Flex>
        </Stack>

        <Text c="chatbox-tertiary" size="xs">
          {strategyHint}
        </Text>
      </Stack>
    </Stack>
  )
}

// src-svelte/src/routes/settings/chat/+page.svelte
<script lang="ts">
	import { getDefaultPrompt } from '$shared/defaults'
	import type { Settings } from '$shared/types'
	import { settingsStore } from '$lib/stores/settings.svelte'

	function toggleSetting<K extends keyof Settings>(key: K, fallback = false) {
		const currentValue = settingsStore.settings[key]
		settingsStore.update({
			[key]: !(typeof currentValue === 'boolean' ? currentValue : fallback),
		} as Partial<Settings>)
	}

	const compactionThreshold = $derived(settingsStore.settings.compactionThreshold ?? 0.6)
</script>

<section class="settings-page">
	<header class="page-header">
		<p class="eyebrow">Chat</p>
		<h1>Conversation defaults and rendering</h1>
		<p>These controls stay limited to the real fields already consumed by the current Svelte chat path.</p>
	</header>

	<div class="stack">
		<section class="card">
			<div class="card-header">
				<h2>Defaults for new conversations</h2>
				<p>Persisted session defaults that feed the actual conversation flow.</p>
			</div>

			<label class="field">
				<span>Default prompt</span>
				<textarea
					rows="4"
					value={settingsStore.settings.defaultPrompt ?? ''}
					oninput={(event) => settingsStore.update({ defaultPrompt: event.currentTarget.value })}
				></textarea>
			</label>

			<div class="action-row">
				<button class="ghost-btn" type="button" onclick={() => settingsStore.update({ defaultPrompt: getDefaultPrompt() })}>
					Reset prompt
				</button>
			</div>

			<div class="range-grid">
				<label class="field">
					<span>Max context message count</span>
					<div class="range-field">
						<input
							type="range"
							min="4"
							max="64"
							step="1"
							value={settingsStore.settings.maxContextMessageCount ?? 20}
							oninput={(event) => settingsStore.update({ maxContextMessageCount: Number(event.currentTarget.value) })}
						/>
						<strong>{settingsStore.settings.maxContextMessageCount ?? 20}</strong>
					</div>
				</label>

				<label class="field">
					<span>Temperature</span>
					<div class="range-field">
						<input
							type="range"
							min="0"
							max="2"
							step="0.1"
							value={settingsStore.settings.temperature ?? 0.7}
							oninput={(event) => settingsStore.update({ temperature: Number(event.currentTarget.value) })}
						/>
						<strong>{(settingsStore.settings.temperature ?? 0.7).toFixed(1)}</strong>
					</div>
				</label>

				<label class="field">
					<span>Top P</span>
					<div class="range-field">
						<input
							type="range"
							min="0"
							max="1"
							step="0.05"
							value={settingsStore.settings.topP ?? 1}
							oninput={(event) => settingsStore.update({ topP: Number(event.currentTarget.value) })}
						/>
						<strong>{(settingsStore.settings.topP ?? 1).toFixed(2)}</strong>
					</div>
				</label>
			</div>

			<label class="switch-row">
				<div class="switch-copy">
					<strong>Stream output</strong>
					<p>Use the current shared stream flag for assistant generation.</p>
				</div>
				<input
					type="checkbox"
					checked={settingsStore.settings.stream ?? true}
					onchange={(event) => settingsStore.update({ stream: event.currentTarget.checked })}
				/>
			</label>
		</section>

		<section class="card">
			<div class="card-header">
				<h2>Display and rendering</h2>
				<p>Only settings already consumed by the Svelte message/markdown path are exposed here.</p>
			</div>

			<div class="switch-stack">
				<label class="switch-row"><div class="switch-copy"><strong>Show word count</strong><p>Show per-message word totals when available.</p></div><input type="checkbox" checked={settingsStore.settings.showWordCount ?? false} onchange={() => toggleSetting('showWordCount')} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Show token usage</strong><p>Show assistant token usage metadata.</p></div><input type="checkbox" checked={settingsStore.settings.showTokenUsed ?? true} onchange={() => toggleSetting('showTokenUsed', true)} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Show model name</strong><p>Show assistant model metadata when it exists.</p></div><input type="checkbox" checked={settingsStore.settings.showModelName ?? true} onchange={() => toggleSetting('showModelName', true)} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Show message timestamp</strong><p>Render timestamp metadata in the message header.</p></div><input type="checkbox" checked={settingsStore.settings.showMessageTimestamp ?? false} onchange={() => toggleSetting('showMessageTimestamp')} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Show first token latency</strong><p>Expose first-token latency if the runtime provides it.</p></div><input type="checkbox" checked={settingsStore.settings.showFirstTokenLatency ?? false} onchange={() => toggleSetting('showFirstTokenLatency')} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Spell check</strong><p>Keep textarea spell-check behavior aligned with shared settings.</p></div><input type="checkbox" checked={settingsStore.settings.spellCheck ?? true} onchange={() => toggleSetting('spellCheck', true)} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Markdown rendering</strong><p>Render markdown in assistant messages.</p></div><input type="checkbox" checked={settingsStore.settings.enableMarkdownRendering ?? true} onchange={() => toggleSetting('enableMarkdownRendering', true)} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>LaTeX rendering</strong><p>Keep math rendering behind the real markdown path.</p></div><input type="checkbox" checked={settingsStore.settings.enableLaTeXRendering ?? true} onchange={() => toggleSetting('enableLaTeXRendering', true)} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Mermaid rendering</strong><p>Render Mermaid diagrams when markdown is enabled.</p></div><input type="checkbox" checked={settingsStore.settings.enableMermaidRendering ?? true} onchange={() => toggleSetting('enableMermaidRendering', true)} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Inject default metadata</strong><p>Preserve automatic metadata like model name and current date.</p></div><input type="checkbox" checked={settingsStore.settings.injectDefaultMetadata ?? true} onchange={() => toggleSetting('injectDefaultMetadata', true)} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Auto-preview artifacts</strong><p>Automatically expand artifact previews when supported.</p></div><input type="checkbox" checked={settingsStore.settings.autoPreviewArtifacts ?? false} onchange={() => toggleSetting('autoPreviewArtifacts')} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Auto-collapse code blocks</strong><p>Keep the current code-collapse default for long replies.</p></div><input type="checkbox" checked={settingsStore.settings.autoCollapseCodeBlock ?? true} onchange={() => toggleSetting('autoCollapseCodeBlock', true)} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Paste long text as a file</strong><p>Keep large pasted content out of the main message body.</p></div><input type="checkbox" checked={settingsStore.settings.pasteLongTextAsAFile ?? true} onchange={() => toggleSetting('pasteLongTextAsAFile', true)} /></label>
				<label class="switch-row"><div class="switch-copy"><strong>Auto-generate titles</strong><p>Allow automatic session renaming when supported by the runtime.</p></div><input type="checkbox" checked={settingsStore.settings.autoGenerateTitle ?? true} onchange={() => toggleSetting('autoGenerateTitle', true)} /></label>
			</div>
		</section>

		<section class="card">
			<div class="card-header">
				<h2>Context management</h2>
				<p>Use the existing compaction settings path without widening any shared contracts.</p>
			</div>

			<label class="switch-row">
				<div class="switch-copy">
					<strong>Auto compaction</strong>
					<p>Automatically summarize and compact history when context usage grows.</p>
				</div>
				<input
					type="checkbox"
					checked={settingsStore.settings.autoCompaction ?? true}
					onchange={() => toggleSetting('autoCompaction', true)}
				/>
			</label>

			<label class="field">
				<span>Compaction threshold</span>
				<div class="range-field">
					<input
						type="range"
						min="0.4"
						max="0.9"
						step="0.05"
						value={compactionThreshold}
						disabled={!(settingsStore.settings.autoCompaction ?? true)}
						oninput={(event) => settingsStore.update({ compactionThreshold: Number(event.currentTarget.value) })}
					/>
					<strong>{Math.round(compactionThreshold * 100)}%</strong>
				</div>
			</label>
		</section>
	</div>
</section>

<style>
	.settings-page {
		height: 100%;
		overflow-y: auto;
		padding: 1rem;
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.page-header,
	.card {
		border: 1px solid var(--chatbox-border-primary);
		border-radius: 18px;
		background: color-mix(in srgb, var(--chatbox-background-secondary), transparent 10%);
		padding: 1rem;
	}

	.eyebrow {
		margin: 0 0 0.22rem;
		font-size: 0.66rem;
		font-weight: 700;
		letter-spacing: 0.08em;
		text-transform: uppercase;
		color: var(--chatbox-tint-tertiary);
	}

	h1,
	h2 {
		margin: 0;
		color: var(--chatbox-tint-primary);
	}

	h1 {
		font-size: 1.1rem;
		line-height: 1.16;
	}

	h2 {
		font-size: 0.95rem;
	}

	.page-header p:last-child,
	.card-header p,
	.switch-copy p {
		margin: 0.38rem 0 0;
		font-size: 0.8rem;
		line-height: 1.45;
		color: var(--chatbox-tint-secondary);
	}

	.stack {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.card-header {
		margin-bottom: 0.85rem;
	}

	.field {
		display: flex;
		flex-direction: column;
		gap: 0.4rem;
	}

	.field + .field,
	.action-row + .range-grid,
	.range-grid + .switch-row {
		margin-top: 0.85rem;
	}

	.field span {
		font-size: 0.76rem;
		font-weight: 700;
		color: var(--chatbox-tint-secondary);
	}

	textarea {
		width: 100%;
		padding: 0.65rem 0.75rem;
		border-radius: 14px;
		border: 1px solid var(--chatbox-border-primary);
		background: var(--chatbox-background-primary);
		color: var(--chatbox-tint-primary);
		font: inherit;
		box-sizing: border-box;
		resize: vertical;
	}

	.action-row {
		display: flex;
		justify-content: flex-end;
		margin-top: 0.75rem;
	}

	.range-grid {
		display: grid;
		grid-template-columns: repeat(3, minmax(0, 1fr));
		gap: 0.8rem;
		margin-top: 0.85rem;
	}

	.range-field,
	.switch-row {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 0.9rem;
		padding: 0.78rem 0.9rem;
		border-radius: 14px;
		border: 1px solid var(--chatbox-border-primary);
		background: var(--chatbox-background-primary);
	}

	.range-field input {
		flex: 1;
		margin: 0;
	}

	.range-field strong,
	.switch-copy strong {
		font-size: 0.84rem;
		color: var(--chatbox-tint-primary);
	}

	.switch-stack {
		display: grid;
		gap: 0.7rem;
	}

	.switch-copy {
		flex: 1;
		min-width: 0;
	}

	.switch-row input {
		width: 1rem;
		height: 1rem;
		flex-shrink: 0;
	}

	.ghost-btn {
		min-height: 2.2rem;
		padding: 0.48rem 0.82rem;
		border-radius: 999px;
		border: 1px solid var(--chatbox-border-primary);
		background: var(--chatbox-background-primary);
		color: var(--chatbox-tint-secondary);
		font-size: 0.8rem;
		font-weight: 700;
		cursor: pointer;
	}

	.ghost-btn:hover {
		background: var(--chatbox-background-secondary);
	}

	@media (max-width: 960px) {
		.range-grid {
			grid-template-columns: minmax(0, 1fr);
		}
	}

	@media (max-width: 720px) {
		.settings-page {
			padding: 0.85rem;
		}

		.range-field,
		.switch-row {
			align-items: flex-start;
			flex-direction: column;
		}

		.action-row {
			justify-content: stretch;
		}
	}
</style>
